### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by PettyBitch** [trigger-death/TerrariaRupeeReplacer#1]
TerrariaRupeeReplacer.Patching.PatcherException: Failed to find starting point '1' for Terraria.Main.DrawInventory
   at TerrariaRupeeReplacer.Patching.Patcher.CheckFailedToFindStart(Int32 start, Int32 index, String function)
   at TerrariaRupeeReplacer.Patching.Patcher.Patch_Main_DrawInventory()
   at TerrariaRupeeReplacer.Patching.Patcher.Patch()
   at TerrariaRupeeReplacer.MainWindow.OnPatch(Object sender, RoutedEventArgs e)

**Comment by trigger-segfault** [comment]
Looks like the patcher needs to be updated for the latest version of tModLoader. I'll keep you updated, and post here and in the forums when it's fixed.

**Comment by trigger-segfault** [comment]
The issue has been fixed, the latest version is now available on GitHub or on the forums. Thanks for the report! :)

**Comment by PettyBitch** [comment]
Thank you.
Sorry for the name, I had to make a quick disposable account to report this issue.

**Comment by trigger-segfault** [comment]
Ah, no problem. ;)
